parameters:
    some_service_parameters:
        registration_name:
            entity:
                class: Foo\BarBundle\Entity\ClassName
                repository: FooBarBundle:ClassName
            form:
                class: Foo\BarBundle\Form\ClassNameType
                service: service.name
            access:
                list: 'ROLE_ADMIN'
                edit: 'ROLE_ADMIN'
                create: 'ROLE_ADMIN'
                delete: 'ROLE_ADMIN'
            misc:
                thumb: bundles/beltonsimpleadmin/images/design/icons/user.png
                panel: true
            menu:
                refer: some_menu
                link: some_link


services:
    belton_simple_admin.manager:
        class: Belton\SimpleAdminBundle\Manager\Manager
        arguments: 
            - "@doctrine.orm.entity_manager"
            - "%belton_simple_admin.manager.registration%"
            - "%belton_simple_admin.manager.menu%"
            - "%belton_simple_admin.manager.infos%"
        calls:
            - [setPaginator, [@knp_paginator]]
            - [setSecurity, [@security.context]]
        tags:
            - {name: twig.extension}